### ISSUE TITLE
USER STORY - Account Social login

### ISSUE THREAD

**Issue by Dhvani-intwala** [Dhvani-intwala/My-Books-Store#15]
# User Story 

As a **User,** I would like **to be able to use my social media account,** so that **I can create an account without typing in details**

## Acceptance Criteria

- As a user, navigate to the registration page then I should have the option to register using my social media account.
- As a user, register using my social media account option then An account should be created using the social media credentials.
- As a user, register using my social media account then I should have the ability to sign into my account using my social media account credentials.

### Tasks

- [ ]  Develop the ability for users to utilize their Google account to register for a user account
- [ ]  Develop the ability for users to utilize their Google account to sign into their account
- [ ]  Develop the ability for users to utilize their Apple account to register for a user account
- [ ]  Develop the ability for users to utilize their Apple account to sign into their account
- [ ]  Develop the ability for users to utilize their Facebook account to register for a user account
- [ ]  Develop the ability for users to utilize their Facebook account to sign into their account
