### ISSUE TITLE
USER STORY - Add Products

### ISSUE THREAD

**Issue by Dhvani-intwala** [Dhvani-intwala/My-Books-Store#16]
# User Story

As an **admin,**  I want **to be able to add a product to store,** so that **I can add new products.**

## Acceptance Criteria

- Being able to create a new products
 
### Tasks

- [ ] Create a Product model
- [ ] Register it in admin panel
- [ ] Create a view for the model so the database can be updated.
